### ISSUE TITLE
Can I rely on this being around for a while? :)

### ISSUE THREAD

**Issue by sinewave440hz** [vexelon-dot-net/e-additives.server#17]
Hi, this seems like a pretty good idea to me and I thought I might build a little app around it to try out some ideas. I managed to get a key from mashape and it works, but the mashape test buttons failed and a couple of the links in the docs (like to this GitHub page for example) 404ed. So given the age of the repo, I just wanted to check the general status of the API and check that it won't disappear any time soon. If I build something worth developing further maybe you would be open to PRs...?

**Comment by petarov** [comment]
Hi,

Short answer is - **Yes**.

Long answer is - It will be around as long as OpenShift is around as a service. The current EAD API is hosted on an [OpenShift PaaS](https://www.openshift.com/) free plan. It's already running for a couple of years now, so I don't see it being broken anytime soon. At least I don't hope so.

That being said, as you yourself already hinted, the project is actually not maintained anymore. PRs are welcome should you want to improve things or update, the now outdated, libs used. 

Cheers 🍺

**Comment by sinewave440hz** [comment]
Thanks. I'll take a look.
